[build]
  command = "npm run build"
  publish="dist"
  base = "medikals/"
  # The base directory should be the path to the nested Vue project


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
